apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
      - name: forgejo
        image: codeberg.org/forgejo/forgejo:8
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 2222
          name: ssh
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: forgejo-data
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-svc
  namespace: forgejo
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: forgejo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo-ingress
  namespace: forgejo
spec:
  rules:
  - host: forgejo.imew.git
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forgejo-svc
            port:
              number: 3000
